export const data = [
  {
    id: 1,
    name: "Смартфон Samsung G...",
    imageUrl: "/1.jpg",
    price: "7 300 000 сум",
    sale_price: "от 2 435 000 сум",
    swop: false,
    gift: true,
    discount: true,
    isIPhone: false,
    amount: 24,
    width: 64,
    height: 136
  },
  {
    id: 2,
    name: "Смартфон Apple iphon...",
    imageUrl: "/2.jpg",
    price: "7 300 000 сум",
    sale_price: "от 2 435 000 сум",
    swop: true,
    gift: false,
    discount: false,
    isIPhone: false,
    amount: 24,
    width: 105,
    height: 142.8
  },
  {
    id: 3,
    name: "Наушники Apple Airpo...",
    imageUrl: "/3.jpg",
    price: "7 300 000 сум",
    sale_price: "от 2 435 000 сум",
    swop: true,
    gift: false,
    discount: false,
    isIPhone: false,
    amount: 24,
    width: 107.1,
    height: 142.8
  },
  {
    id: 4,
    name: "Samsung Galaxy Z Fold...",
    imageUrl: "/4.jpg",
    price: "7 300 000 сум",
    sale_price: "от 2 435 000 сум",
    swop: false,
    gift: true,
    discount: true,
    isIPhone: false,
    amount: 24,
    width: 104,
    height: 138
  },
  {
    id: 5,
    name: "Смартфон Apple iphon...",
    imageUrl: "/2.jpg",
    price: "7 300 000 сум",
    sale_price: "от 2 435 000 сум",
    swop: true,
    gift: false,
    discount: false,
    isIPhone: false,
    amount: 24,
    width: 105,
    height: 142.8
  },
  {
    id: 6,
    name: "Смартфон Samsung G...",
    imageUrl: "/1.jpg",
    price: "7 300 000 сум",
    sale_price: "от 2 435 000 сум",
    swop: false,
    gift: true,
    discount: true,
    isIPhone: false,
    amount: 24,
    width: 64,
    height: 136
  },
  {
    id: 7,
    name: "Смартфон Apple iphon...",
    imageUrl: "/2.jpg",
    price: "7 300 000 сум",
    sale_price: "от 2 435 000 сум",
    swop: true,
    gift: false,
    discount: false,
    isIPhone: false,
    amount: 24,
    width: 105,
    height: 142.8
  },
  {
    id: 8,
    name: "Наушники Apple Airpo...",
    imageUrl: "/3.jpg",
    price: "7 300 000 сум",
    sale_price: "от 2 435 000 сум",
    swop: true,
    gift: false,
    discount: false,
    isIPhone: false,
    amount: 24,
    width: 107.1,
    height: 142.8
  },
  {
    id: 9,
    name: "Samsung Galaxy Z Fold...",
    imageUrl: "/4.jpg",
    price: "7 300 000 сум",
    sale_price: "от 2 435 000 сум",
    swop: false,
    gift: true,
    discount: true,
    isIPhone: false,
    amount: 24,
    width: 104,
    height: 138
  },
  {
    id: 10,
    name: "Смартфон Apple iphon...",
    imageUrl: "/2.jpg",
    price: "7 300 000 сум",
    sale_price: "от 2 435 000 сум",
    swop: true,
    gift: false,
    discount: false,
    isIPhone: false,
    amount: 24,
    width: 105,
    height: 142.8
  }
]